[package]
name = "redstone"
version = "1.0.0"
edition = "2021"

[dependencies]
rfd = "0.11.4"
tokio = { version = "1", features = ["net", "fs", "io-util", "macros", "rt-multi-thread"] }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true